//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinmuSample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KinmuSampleDataEntities : DbContext
    {
        public KinmuSampleDataEntities()
            : base("name=KinmuSampleDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kinmu> kinmu { get; set; }
        public virtual DbSet<m_bumon> m_bumon { get; set; }
        public virtual DbSet<m_gamen> m_gamen { get; set; }
        public virtual DbSet<m_kojin> m_kojin { get; set; }
    }
}
