//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinmuSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_gamen
    {
        public int id { get; set; }
        public int company_code { get; set; }
        public int screen_code { get; set; }
        public int item_code { get; set; }
        public int hyouji { get; set; }
    }
}
