//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinmuSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_kojin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_kojin()
        {
            this.kinmu = new HashSet<kinmu>();
        }
    
        public int id { get; set; }
        public int bumon_id { get; set; }
        public string kojin_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kinmu> kinmu { get; set; }
        public virtual m_bumon m_bumon { get; set; }
    }
}
